#!/bin/bash
# Proxmox Hook Script for port forwarding

set -eu

VMID=$1
PHASE=$2

# System specific parameters
BRIDGE=""
HOSTADDR=""

echo "$PHASE"

# Exit if not relevant phase
if [[ $PHASE != "pre-start" && $PHASE != "post-start" && "$PHASE" != "pre-stop" ]]; then
	exit
fi

service_exists() {
	# Expects param 1 to be the service name
	if systemctl list-unit-files "$1.service" >/dev/null; then
		return 0
	else
		return 1
	fi
}

mod_iptables() {
	#Adds or removes iptables rules - paramters are action and rule. Use 'add' to add rule, anything else to remove it. Recommend 'remov' or 'delet' for logging purposes
	if [[ "$1" == "add" ]]; then
		ACTION="-A"
	else
		ACTION="-D"
	fi
	iptables -t nat $ACTION PREROUTING $2 && echo "iptables rule '$2' $1ed" || echo "Error $1ing rule '$2'"
}

add_forward() {
	FWORIGADDR=$1
	FWPROTO=$2
	FWORIGPORT=$3
	FWTOADDR=$4
	FWTOPORT=${5:-$FWORIGPORT}

	if service_exists "socat-forwarder-$FWPROTO@"; then
		# Start a systemd service to forward the ports with socat
		FWDR="$FWPROTO@$FWORIGPORT-$FWTOADDR:$FWTOPORT"
		systemctl start "socat-forwarder-$FWDR" && echo "Started socat forwarder $FWDR" || echo "Error starting socat forwarder $FWDR"
	else
		# Use iptables rules to forward the port
		mod_iptables "add" "-p $FWPROTO -d $FWORIGADDR -m $FWPROTO --dport $FWORIGPORT -j DNAT --to-destination $FWTOADDR:$FWTOPORT"
	fi
}

remove_forward() {
	FWORIGADDR=$1
	FWPROTO=$2
	FWORIGPORT=$3
	FWTOADDR=$4
	FWTOPORT=${5:-$FWORIGPORT}

	if service_exists "socat-forwarder-$FWPROTO@"; then
		# Stop a systemd service to forward the ports with socat
		FWDR="$FWPROTO@$FWORIGPORT-$FWTOADDR:$FWTOPORT"
		systemctl stop "socat-forwarder-$FWDR" || echo "Error stopping socat forwarder $FWDR"
	else
		# Use iptables rules to forward the port
		mod_iptables "remov" "-p $FWPROTO -d $FWORIGADDR -m $FWPROTO --dport $FWORIGPORT -j DNAT --to-destination $FWTOADDR:$FWTOPORT"
	fi
}

# Determine Host address to use (for iptables rules) if not already set
if [[ -z "$HOSTADDR" ]]; then
	if [[ -z "$BRIDGE" ]]; then
		HOSTADDR=$(ip addr show | grep -Eo 'inet\s+\S+/' | sed 's/^.*inet\s//;s|/||' | grep -v '^127\.' | head -n 1)
	else
		HOSTADDR=$(ip addr show dev $BRIDGE | grep -Eo 'inet\s+\S+/' | sed 's/^.*inet\s//;s|/||' | grep -v '^127\.' | head -n 1)
	fi
fi

# Get configuration information for machine
if qm conf $VMID >/dev/null 2>&1; then
	FWDDATA=$(qm config $VMID | grep "^description" | sed -E 's/^.*: //;s/^.*port-forwards(%3A)?%0A//I;s/%0A%0A.*$//Ig;s/%3A/:/g;s/%0A/\n/g')
	# Find the first IP address configured in cloud-init settings
	ADDRESS="$(qm config $VMID 2>/dev/null | grep "^ipconfig" | sed 's/^.*: //' | grep -Po '(?<=ip=)\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b' | head -n 1)"
else
	FWDDATA=$(pct config $VMID | grep "^description" | sed -E 's/^.*: //;s/^.*port-forwards(%3A)?%0A//I;s/%0A%0A.*$//Ig;s/%3A/:/g;s/%0A/\n/g')
	# Find the first IP address statically configured in config
	ADDRESS=$(pct config $VMID | grep "^net" | sed 's/^.*: //' | grep -Po '\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b' | head -n 1)
fi

echo "Port forward script running $PHASE for $VMID and detected parameters as Host: $HOSTADDR, Bridge: $BRIDGE, VM Addr: $ADDRESS"
# Extract port forwarding configuration from description
# Extracts data lines from a line ending with "port-forwards:" to a double new line and converts encoded symbols

# If no data was found, exit the hook
if [[ -z "$FWDDATA" ]]; then
	exit
fi

echo "Processing port forwarding"

PROTO="tcp"
echo "$FWDDATA" | while read linedata
do
	# Look for line updating the address to use (will override anything found from net config lookups)
	if [[ "$linedata" =~ "addr.*:.+" ]]; then
		# Extract an IPv4 address - use this as destination until updated
		ADDRESS=$(echo "$linedata" | grep -Po '\b\d{1,3}\.\d{1.3}\.\d{1.3}\.\d{1.3}\b')
	# Look for protocol type in line - use this as the protocol until changed
	elif [[ "$linedata" =~ "tcp" ]]; then
		PROTO="tcp"
	elif [[ "$linedata" =~ "udp" ]]; then
		PROTO="udp"
	elif [[ "$linedata" =~ ^[^0-9]*[0-9]{1,5}[^0-9]+[0-9]{1,5}[^0-9]*$ ]]; then
		# Line contains two 1-5 digit numbers separated by non-digits
		SPORT=$(echo "$linedata" | sed -E 's/^[^0-9]*([0-9]+)[^0-9]+([0-9]+)[^0-9]*$/\1/')
		DPORT=$(echo "$linedata" | sed -E 's/^[^0-9]*([0-9]+)[^0-9]+([0-9]+)[^0-9]*$/\2/')
		# Exit if no static address configuration. TODO - Handle dynamic addresses through QEMU guest agent or lxc-info
		if [[ "$PHASE" == "pre-start" ]]; then
			if [[ -z "$ADDRESS" ]]; then
				echo "Address not found in configuration or description. Use an address line to force this."
				exit 126
			fi
		elif [[ "$PHASE" == "post-start" ]]; then
			add_forward $HOSTADDR $PROTO $SPORT $ADDRESS $DPORT
		elif [[ "$PHASE" == "pre-stop" ]]; then
			remove_forward $HOSTADDR $PROTO $SPORT $ADDRESS $DPORT
		fi
	fi
done
